### ISSUE TITLE
Unable to install the .pkg on macOS (arm64 and x86_64)

### ISSUE THREAD

**Issue by watjurk** [radareorg/iaito#44]
## Environment Details

MacBook Pro (13-inch, M1, 2020)
Big Sur 11.3 (20E232)

```sh
zsh: command not found: iaito
Wed May  5 14:23:31 CEST 2021
radare2 5.2.0 0 @ darwin-arm-64 git.
commit: HEAD build: 2021-04-11__23:39:32
Darwin arm64
```

## Description

When I try to install iaito I am getting a following error:
<img width="255" alt="Screenshot" src="https://user-images.githubusercontent.com/21204727/117140471-bdc9d280-adad-11eb-8e4d-86a675b661bc.png">
Related to: #6

**Comment by trufae** [comment]
I can confirm the issue on x86_64, so it's not an M1-specific issue, the .pkg has not been generated properly in the CI. i'll recheck this and make a new release when fixed.

**Comment by lATAl** [comment]
Any update @trufae ?

**Comment by radare** [comment]
Fixed in https://github.com/radareorg/iaito/commit/054e60d1fc551ee5ba581c9c0dbe47386aeba75e

will update the pkg in the next release in around 2 weeks. but the CI is now generating valid .pkg files :)

thanks for reporting!

**Comment by radare** [comment]
ideally we should ship x64 and arm64 builds. but for now its x64 only

**Comment by pinkeen** [comment]
I have downloaded the CI built releases both from master and the mentioned commit (054e60d1fc551). Still the same error during unzipping;
![Screenshot 2021-08-03 at 23 58 50](https://user-images.githubusercontent.com/2019132/128091985-81b1e52e-49d1-4c04-8ee8-15ce8f870850.png)

However, this time, the installer starts but fails:
![Screenshot 2021-08-03 at 23 59 11](https://user-images.githubusercontent.com/2019132/128092012-bd60d871-77d6-40b3-a1a3-ab9d5fa9871b.png)

Still seems to me like a corrupted zip archive.

**Comment by trufae** [comment]
reopening, will look into that when i have time (R). if you do, feel free to contribute

**Comment by trufae** [comment]
by running `log stream` in a terminal i find out the following error message:

`Installer: (Install) Package /tmp/iaito-5.3.1.pkg uses a deprecated pre-10.2 format (or uses a newer format but is invalid).`

So.. as long as the pkg format is a little messy i just decided to go for zipping the .app, that way it's up to the user to drag and drop it wherever they want and `r2env` can do the $PATH symlink if needed to get it working from the shell.

I'm seeing an issue with the icon when compiled now, but as long as all this is related to the qt machinery i will wait for the ci to see if that works as expected.

I'll cut a release soon after fixing few more bugs in iaito and then go back to r2env to integrate it for macOS

thanks for reporting! i wasnt suposed to be maintaining this but guess i should do everything as usual :D so stay tuned. ill come back with more candies soon.
